import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useRef } from "react";
import { Parallax, ParallaxLayer } from "@react-spring/parallax";

import Balloon from "../public/Balloon";

import Background from "../components/Background";

export default function Home() {
  return (
    <div>
      <Background />
      <Parallax pages={1.49} style={{ top: "0", left: "0" }}>
        <Head>
          <title>Carnival Communication at FIU</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ParallaxLayer offset={0.5} speed={0.3}>
          <Balloon
            className={styles.backBalloons}
            stroke="#050404"
            fill="#1098f7"
            highlight="#FFECD1"
          />
          <Balloon
            className={styles.backBalloons}
            stroke="#050404"
            fill="red"
            highlight="#FFECD1"
          />
        </ParallaxLayer>
        <main className={styles.main}>
          <ParallaxLayer factor={0} offset={0} speed={0.0001}>
            <h1 className={styles.title}>
              Carnival Communication
              <br />
              at FIU
            </h1>
          </ParallaxLayer>
          <ParallaxLayer factor={1.5} offset={0.9} speed={1.35}>
            <div className={styles.aboutDiv}>
              <svg
                viewBox="0 0 1440 192"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  className={styles.aboutWave}
                  d="M0 32.4381L40 21.7674C80 11.4956 160 -10.4441 240 5.81125C320 21.4683 400 75.3204 480 106.934C560 139.145 640 149.118 720 154.802C800 160.088 880 160.088 960 138.846C1040 117.205 1120 75.3204 1200 75.0212C1280 75.3204 1360 117.205 1400 138.846L1440 160.088V192H1400C1360 192 1280 192 1200 192C1120 192 1040 192 960 192C880 192 800 192 720 192C640 192 560 192 480 192C400 192 320 192 240 192C160 192 80 192 40 192H0V32.4381Z"
                />
              </svg>

              <div className={styles.aboutSpacer}></div>

              <svg
                viewBox="0 0 1440 192"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  className={styles.aboutWave}
                  d="M1440 159.562L1400 170.233C1360 180.504 1280 202.444 1200 186.189C1120 170.532 1040 116.68 960 85.0664C880 52.8549 800 42.8822 720 37.1978C640 31.9124 560 31.9124 480 53.154C400 74.7946 320 116.68 240 116.979C160 116.68 80 74.7946 40 53.154L0 31.9124V0H40C80 0 160 0 240 0C320 0 400 0 480 0C560 0 640 0 720 0C800 0 880 0 960 0C1040 0 1120 0 1200 0C1280 0 1360 0 1400 0H1440V159.562Z"
                />
              </svg>
            </div>
          </ParallaxLayer>
          <ParallaxLayer factor={1} offset={0.99} speed={1}>
            <section className={styles.aboutContent}>
              <h2>About Us</h2>
              <p>
                Carnival Communication at FIU is a student organization
                dedicated to helping everyone to disconnect from their devices
                and connect with each other in meaningful conversations. After
                attending, students will realize they don’t need their phone
                with them in order to have a good time and will be more
                comfortable engaging with anybody they are confronted with
                throughout their days.
              </p>
            </section>
          </ParallaxLayer>
        </main>
        <ParallaxLayer offset={0.5} speed={1}>
          <Balloon
            className={styles.frontBalloons}
            stroke="#050404"
            fill="#eee82c"
            highlight="#FFECD1"
          />
          <Balloon
            className={styles.frontBalloons}
            stroke="#050404"
            fill="#52489c"
            highlight="#FFECD1"
          />
        </ParallaxLayer>
      </Parallax>
    </div>
  );
}
